_name_: genomic_dna_mlm

data_dir: ${oc.env:MAIZE_DNA_INDEXED_DIR,data/processed/maize_dna}
sequence_type: dna
species: maize

tokenizer_name: char
window_size: 10240
mlm: true
mlm_probability: 0.15

batch_size: 1
batch_size_eval: 1
shuffle: true
split_seed: 2357
require_nonempty_splits: true

max_train_windows: null
max_val_windows: null
max_test_windows: null
